plugins {
    id "java"
    id "fabric-loom" version "1.17.13" apply false
    id "net.neoforged.moddev" version "2.0.141" apply false
}

def mcDlssVersion = providers.gradleProperty("mcDlssVersion")
        .orElse("0.1.0-SNAPSHOT")

allprojects {
    group = "dev.mcdlss"
    version = mcDlssVersion.get()
}

subprojects {
    apply plugin: "java"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 21
    }
}
